El álgebra lineal es una rama de las matemáticas que estudia las estructuras algebraicas y sus aplicaciones. En Python, se puede utilizar para resolver una amplia variedad de problemas en una variedad de campos, como ciencia de datos, ingeniería, física y economía. Aquí hay un temario resumido de los conceptos básicos de álgebra lineal que se pueden aprender y aplicar en Python:
1.Vectores y operaciones vectoriales: Aprenderás a trabajar con vectores y cómo realizar operaciones como la suma, resta y multiplicación de vectores.


Un vector es un objeto matemático que se representa como una lista de números, donde cada número representa una componente del vector. En Python, podemos crear vectores utilizando la biblioteca NumPy, que es una biblioteca de cálculo científico popular.

Aquí hay un ejemplo de código para crear dos vectores y realizar la suma de ellos:

In [1]:
import numpy as np

vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
vector_sum = vector_a + vector_b

print(vector_sum)

[5 7 9]


Como puedes ver, la suma de vectores es simplemente la suma componente a componente.

Además de la suma, también podemos realizar otras operaciones vectoriales, como la resta y la multiplicación por un escalar. Aquí hay un ejemplo de código para realizar la resta y la multiplicación por un escalar:

In [2]:
import numpy as np

vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
vector_diff = vector_a - vector_b
vector_scaled = 2 * vector_a

print(vector_diff)
print(vector_scaled)

[-3 -3 -3]
[2 4 6]


Otro concepto importante en álgebra lineal es la multiplicación de vectores, específicamente la multiplicación interna o producto escalar. El producto escalar entre dos vectores es un número que se obtiene sumando el producto de cada componente correspondiente.

Aquí hay un ejemplo de código que muestra cómo realizar el producto escalar de dos vectores en Python utilizando NumPy:

In [3]:
import numpy as np

vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
dot_product = np.dot(vector_a, vector_b)

print(dot_product)

32


El producto escalar es un número que se utiliza para medir la similitud entre dos vectores. Si dos vectores son paralelos y apuntan en la misma dirección, su producto escalar será un número positivo grande. Por otro lado, si dos vectores son ortogonales y apuntan en direcciones opuestas, su producto escalar será cero.

Además del producto escalar, también existe el producto vectorial o producto cruz. Este es un producto entre dos vectores que resulta en un tercer vector perpendicular a los dos vectores originales. En Python, podemos calcular el producto cruz utilizando la función cross de la biblioteca NumPy.

Aquí hay un ejemplo de código que muestra cómo realizar el producto cruz de dos vectores en Python:

Calcule el segundo componente del producto cruz: vector_a[2] * vector_b[0] - vector_a[0] * vector_b[2] = 3 * 4 - 1 * 6 = 12 - 6 = 6.
Calcule el tercer componente del producto cruz: vector_a[0] * vector_b[1] - vector_a[1] * vector_b[0] = 1 * 5 - 2 * 4 = 5 - 8 = -3.

In [4]:
import numpy as np

vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
cross_product = np.cross(vector_a, vector_b)

print(cross_product)

[-3  6 -3]


2.LA MATRIZ
 Las matrices son arreglos bidimensionales de números que se utilizan para representar sistemas lineales. Por ejemplo, si tenemos un sistema de dos ecuaciones lineales, podemos representarlo como una matriz:

1x + 2y = 7
3x + 4y = 8
La matriz equivalente sería:
[[1, 2, 7],
 [3, 4, 8]]


En Python, podemos utilizar la biblioteca NumPy para crear y manipular matrices. Aquí hay un ejemplo de código que muestra cómo crear una matriz en Python utilizando NumPy:

In [6]:
import numpy as np

matrix = np.array([[1, 2, 7],
                   [3, 4, 8]])

print(matrix)


[[1 2 7]
 [3 4 8]]


Además de crear matrices, también podemos realizar operaciones con matrices como la suma, la multiplicación y la inversión. Aquí hay un ejemplo de código que muestra cómo realizar la suma de dos matrices en Python utilizando NumPy:

In [7]:
import numpy as np

matrix_a = np.array([[1, 2, 7],
                     [3, 4, 8]])
matrix_b = np.array([[2, 3, 4],
                     [5, 6, 7]])
sum_matrix = np.add(matrix_a, matrix_b)

print(sum_matrix)

[[ 3  5 11]
 [ 8 10 15]]


Otro concepto importante en álgebra lineal es la multiplicación de matrices. La multiplicación de matrices es una operación que se realiza entre dos matrices y produce una matriz resultante. La regla básica de la multiplicación de matrices es que el número de columnas de la primera matriz debe ser igual al número de filas de la segunda matriz.

Aquí hay un ejemplo de código que muestra cómo realizar la multiplicación de dos matrices en Python utilizando NumPy:
La multiplicación de matrices se realiza de la siguiente manera:

Primero, se multiplica el primer elemento de la primera fila de matrix_a (1) por el primer elemento de la primera columna de matrix_b (2), y se multiplica el segundo elemento de la primera fila de matrix_a (2) por el segundo elemento de la primera columna de matrix_b (4): 1 * 2 + 2 * 4 = 2 + 8 = 10. Este valor se coloca en la primera fila y primera columna de la matriz resultante.
Luego, se multiplica el primer elemento de la primera fila de matrix_a (1) por el segundo elemento de la primera columna de matrix_b (3), y se multiplica el segundo elemento de la primera fila de matrix_a (2) por el segundo elemento de la segunda columna de matrix_b (5): 1 * 3 + 2 * 5 = 3 + 10 = 13. Este valor se coloca en la 

In [8]:
import numpy as np

matrix_a = np.array([[1, 2],
                     [3, 4]])
matrix_b = np.array([[2, 3],
                     [4, 5]])
product_matrix = np.dot(matrix_a, matrix_b)

print(product_matrix)


[[10 13]
 [22 29]]


Otro concepto importante en álgebra lineal es la multiplicación de matrices. La multiplicación de matrices es una operación que se realiza entre dos matrices y produce una matriz resultante. La regla básica de la multiplicación de matrices es que el número de columnas de la primera matriz debe ser igual al número de filas de la segunda matriz.

Aquí hay un ejemplo de código que muestra cómo realizar la multiplicación de dos matrices en Python utilizando NumPy:

In [9]:
import numpy as np

matrix_a = np.array([[1, 2],
                     [3, 4]])
matrix_b = np.array([[2, 3],
                     [4, 5]])
product_matrix = np.dot(matrix_a, matrix_b)

print(product_matrix)


[[10 13]
 [22 29]]


Además de la multiplicación de matrices, también es importante conocer la transposición de matrices. La transposición de una matriz consiste en intercambiar sus filas por sus columnas. Aquí hay un ejemplo de código que muestra cómo realizar la transposición de una matriz en Python utilizando NumPy:

In [10]:
import numpy as np

matrix = np.array([[1, 2, 7],
                   [3, 4, 8]])
transposed_matrix = np.transpose(matrix)

print(transposed_matrix)


[[1 3]
 [2 4]
 [7 8]]


3.Espacio vectorial: Aprenderás acerca de los espacios vectoriales y cómo se utilizan para describir relaciones matemáticas.

Un espacio vectorial es un conjunto de vectores que cumplen ciertas propiedades, como la adición y la multiplicación escalar.

El concepto de base y dimensión es fundamental en el álgebra lineal. Una base de un espacio vectorial es un conjunto de vectores linearly independientes que pueden combinarse para formar cualquier vector en el espacio vectorial. La dimensión de un espacio vectorial es el número de vectores en su base.

Otro concepto importante en álgebra lineal es el producto interno, también conocido como producto escalar. El producto interno entre dos vectores se define como el producto de sus componentes y la suma de estos productos. El producto interno puede utilizarse para medir la similitud entre dos vectores.

Aquí hay un ejemplo de código que muestra cómo realizar el producto interno entre dos vectores en Python utilizando NumPy:

En este caso, el producto escalar de vector_a y vector_b es 20. Es decir, vector_a y vector_b son vectores en un espacio tridimensional y su producto escalar es igual a la suma de los productos de sus componentes correspondientes: 1 * 2 + 2 * 3 + 3 * 4 = 20.

In [11]:
import numpy as np

vector_a = np.array([1, 2, 3])
vector_b = np.array([2, 3, 4])

dot_product = np.dot(vector_a, vector_b)

print(dot_product)


20


El producto interno también se puede utilizar para calcular la magnitud de un vector, que es la raíz cuadrada de la suma de los cuadrados de sus componentes. Aquí hay un ejemplo de código que muestra cómo calcular la magnitud de un vector en Python utilizando NumPy:

Calcular la magnitud del vector mediante la función np.linalg.norm(). Esta función toma como entrada un vector y devuelve su magnitud. La magnitud de un vector en un espacio n-dimensional se define como la raíz cuadrada de la suma de los cuadrados de sus componentes. Por ejemplo, si vector = [a1, a2, a3], la magnitud sería sqrt(a1^2 + a2^2 + a3^2). sqrt de 14

In [12]:
import numpy as np

vector = np.array([1, 2, 3])

magnitude = np.linalg.norm(vector)

print(magnitude)


3.7416573867739413



Un espacio vectorial es una colección de vectores que se pueden sumar y multiplicar por un escalar. Los vectores en un espacio vectorial cumplen ciertas propiedades, como la asociatividad y la conmutatividad de la suma, y la distributividad de la multiplicación escalar con respecto a la suma.

En álgebra lineal, es importante tener en cuenta las propiedades de los espacios vectoriales para poder realizar operaciones y resolver problemas.

Un ejemplo de un espacio vectorial es el espacio R^n, que es el conjunto de todas las tuplas de n números reales. Cada tupla es un vector en el espacio R^n.

Otro ejemplo de un espacio vectorial es el espacio de matrices. Una matriz es un arreglo rectangular de números, y el espacio de matrices es el conjunto de todas las matrices. Las matrices se pueden sumar y multiplicar por un escalar, y cumplen las propiedades de los espacios vectoriales.

Aquí hay un ejemplo de código que muestra cómo sumar y multiplicar matrices por un escalar en Python utilizando NumPy:

explicacion matrix_sum = [[1 2] + [2 3]
                         [3 4] + [4 5]]

In [13]:
import numpy as np

matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[2, 3], [4, 5]])

matrix_sum = matrix_a + matrix_b
#matrix_sum = [[1 2] + [2 3] [3 4] + [4 5]]
matrix_scaled = 2 * matrix_a

print(matrix_sum)
print(matrix_scaled)


[[3 5]
 [7 9]]
[[2 4]
 [6 8]]


Además de las operaciones básicas de suma y multiplicación escalar, en álgebra lineal también es importante conocer el concepto de subespacio. Un subespacio es un espacio vectorial dentro de otro espacio vectorial. Por ejemplo, el espacio de las matrices diagonales es un subespacio del espacio de matrices.

Para determinar si un conjunto de vectores es un subespacio de un espacio vectorial, deben cumplirse ciertas propiedades, como la certeza de que la suma de dos vectores en el conjunto también está en el conjunto y que cualquier multiplicación escalar de un vector en el conjunto también está en el conjunto.

Estos son algunos de los conceptos básicos de los espacios vectoriales en álgebra lineal. Conocer estos conceptos te ayudará a entender y aplicar operaciones y técnicas más avanzadas en álgebra lineal, y te permitirá resolver problemas complejos en una amplia variedad de de áreas, como la ingeniería, la física, la economía y la biología.

Además de los espacios vectoriales, también es importante conocer otros conceptos en álgebra lineal, como la notación matricial, los sistemas lineales, las transformaciones lineales, las matrices inversas y las matrices ortogonales.

La notación matricial es una forma conveniente de representar y manipular sistemas lineales. Un sistema lineal es un conjunto de ecuaciones lineales que describen una relación matemática entre variables desconocidas.

Las transformaciones lineales son funciones que transforman un vector en otro vector en un espacio vectorial. Las transformaciones lineales se pueden representar mediante matrices, y se pueden combinar para crear transformaciones más complejas.

Las matrices inversas son matrices que, cuando se multiplican por otra matriz, dan como resultado la matriz identidad. Las matrices inversas son útiles para resolver sistemas lineales y para realizar otras operaciones en álgebra lineal.

Las matrices ortogonales son matrices cuya inversa es igual a su traspuesta. Las matrices ortogonales se utilizan en muchas aplicaciones en álgebra lineal, como la rotación de vectores en un espacio tridimensional.

Estos son solo algunos de los conceptos básicos de álgebra lineal, y hay muchos otros que se pueden profundizar a medida que avanzas en tu aprendizaje. Pero conocer estos conceptos te dará una base sólida para entender y aplicar álgebra lineal en diferentes contextos.

En resumen, para aprender álgebra lineal con Python, es importante conocer los conceptos básicos de vectores y operaciones vectoriales, espacios vectoriales, notación matricial, sistemas lineales, transformaciones lineales, matrices inversas y matrices ortogonales. También es importante tener una buena comprensión de las propiedades de los espacios vectoriales y las operaciones que se pueden realizar con ellos.

Notación matricial.

La notación matricial es una forma de representar y manipular sistemas lineales. Una matriz es simplemente un arreglo rectangular de números o funciones. Las matrices se pueden utilizar para representar transformaciones lineales, y también se pueden utilizar para resolver sistemas lineales.

Las operaciones básicas con matrices incluyen la adición, la multiplicación por un escalar y la multiplicación de matrices. La multiplicación de matrices es una operación importante en álgebra lineal, ya que permite combinar transformaciones lineales para crear transformaciones más complejas.

En Python, se pueden crear matrices utilizando una biblioteca como NumPy, que proporciona una amplia gama de funciones para trabajar con matrices. Por ejemplo, aquí está cómo crear una matriz en NumPy:

In [14]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
print(A)


[[1 2]
 [3 4]]


Este código crea una matriz de dos filas y dos columnas, y la imprime en la pantalla.

Además de las operaciones básicas con matrices, también es importante conocer el concepto de inversa de una matriz y cómo se puede utilizar para resolver sistemas lineales. La inversa de una matriz es otra matriz que, cuando se multiplica por la matriz original, da como resultado la matriz identidad.

Aquí está un ejemplo de cómo se puede utilizar la inversa de una matriz para resolver un sistema lineal en Python:

In [15]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
x = np.linalg.inv(A).dot(b)
print(x)


[-4.   4.5]


Este código crea una matriz A y un vector b, y luego resuelve el sistema lineal Ax = b utilizando la inversa de A y la multiplicación matricial.

Diagonalización de matrices.



a diagonalización de una matriz es un proceso que permite transformar una matriz en una forma diagonal, es decir, una matriz en la que todos los elementos fuera de la diagonal principal son cero.

La diagonalización es importante en álgebra lineal porque permite simplificar la forma de una matriz, lo que a su vez permite comprender y analizar sus propiedades y transformaciones. Además, la diagonalización también se utiliza en aplicaciones prácticas como la resolución de sistemas dinámicos y la optimización.

Para diagonalizar una matriz, se requiere encontrar una matriz diagonalizadora y una matriz inversa diagonalizadora, que se multiplican por la matriz original para obtener la forma diagonal.

En Python, se puede utilizar la biblioteca NumPy para diagonalizar una matriz. Por ejemplo, aquí está cómo se puede diagonalizar una matriz en NumPy:





In [16]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)


[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


Este código utiliza la función eig de NumPy para calcular los valores propios y los vectores propios de la matriz A, que se utilizan para construir la matriz diagonalizadora.

Estos son solo algunos de los conceptos básicos de la diagonalización de matrices en álgebra lineal, y hay muchos otros que se pueden profundizar a medida que avanzas en tu aprendizaje. Pero conocer estos conceptos te dará una base sólida para entender y aplicar la diagonalización en diferentes contextos.

Sistemas lineales

Un sistema lineal de ecuaciones es un conjunto de ecuaciones lineales con incógnitas. Los sistemas lineales se utilizan en una amplia variedad de aplicaciones, incluyendo la optimización, la modelación económica y la ingeniería.

En álgebra lineal, existen diferentes métodos para resolver sistemas lineales, incluyendo el método de eliminación de Gauss, el método de sustitución y el método de matrices. Cada método tiene sus propias ventajas y desventajas, y se pueden utilizar en función de las características de cada sistema específico.

En Python, se puede utilizar la biblioteca NumPy para resolver sistemas lineales. Por ejemplo, aquí está cómo se puede resolver un sistema lineal con NumPy:

In [17]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
b = np.array([1, 2])
x = np.linalg.solve(A, b)
print(x)


[0.  0.5]


Este código utiliza la función solve de NumPy para resolver el sistema lineal representado por la matriz A y el vector b. La función devuelve una solución x que cumple con las ecuaciones lineales.

La diagonalización es un proceso que permite transformar una matriz en una matriz diagonal, es decir, una matriz en la que todos los elementos fuera de la diagonal principal son cero. La diagonalización es útil porque permite simplificar cálculos y analizar la estructura de la matriz.

La reducción a forma canónica es un proceso que permite transformar una matriz en una forma estandarizada que facilita su análisis. Hay diferentes formas canónicas, como la forma escalonada, la forma escalonada reducida y la forma Jordan.

En Python, se pueden utilizar las funciones de NumPy para calcular la diagonalización y la reducción a forma canónica. Por ejemplo, aquí está cómo se puede diagonalizar una matriz con NumPy:

In [18]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)


[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


Este código utiliza la función eig de NumPy para calcular los valores propios y vectores propios de la matriz A. Los valores propios representan la diagonal de la matriz diagonalizada, mientras que los vectores propios representan las columnas de la matriz de transformación.

matriz inversa

La matriz inversa es una matriz que, cuando se multiplica por la matriz original, produce la matriz identidad. La matriz inversa es útil porque permite resolver sistemas lineales de ecuaciones, es decir, encontrar las incógnitas en un sistema de ecuaciones lineales.

En Python, se puede calcular la inversa de una matriz con la función inv de NumPy:

In [19]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)
print(A_inv)


[[-2.   1. ]
 [ 1.5 -0.5]]


Una vez que se tiene la matriz inversa, se puede utilizar para resolver sistemas de ecuaciones lineales. Por ejemplo, aquí está cómo se puede resolver el siguiente sistema de ecuaciones lineales con la matriz inversa:

In [20]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])
X = np.linalg.inv(A).dot(B)
print(X)


[-4.   4.5]


Este código utiliza la matriz inversa de A para resolver el sistema de ecuaciones lineales AX = B, donde X representa las incógnitas.

Diagonalización de matrices y su aplicación en la resolución de sistemas de ecuaciones.

La diagonalización de matrices es un proceso mediante el cual se transforma una matriz en una matriz diagonal, es decir, una matriz en la que los elementos fuera de la diagonal principal son cero. La diagonalización es útil porque permite resolver fácilmente sistemas de ecuaciones lineales y, además, permite entender mejor la estructura de la matriz original.

En Python, se puede diagonalizar una matriz utilizando la biblioteca NumPy y su función eig:

In [22]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)


Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


La función eig devuelve los autovalores y autovectores de la matriz A, que se pueden utilizar para diagonalizar la matriz.

Además, la diagonalización también es útil para resolver sistemas de ecuaciones lineales, ya que permite convertir el sistema de ecuaciones en una forma diagonal, lo que hace más fácil resolver las incógnitas.

Estos son solo algunos de los conceptos básicos de la diagonalización de matrices y su aplicación en la resolución de sistemas de ecuaciones, y hay muchos otros que se pueden profundizar a medida que avanzas en tu aprendizaje. Pero conocer estos conceptos te dará una base sólida para entender y aplicar la diagonalización de matrices en diferentes contextos.






reducción de forma canónica de una matriz

También conocida como forma normal de Jordan (JNF, por sus siglas en inglés). La JNF es una representación de una matriz en la que los eigenvalores aparecen en la diagonal principal y los eigenvectores están en las subdiagonales inmediatamente debajo de la diagonal principal.

La JNF es útil porque permite entender la estructura de una matriz y su relación con los eigenvalores y eigenvectores. Además, la JNF se utiliza a menudo en el análisis de sistemas dinámicos, ya que permite entender cómo se comportan los sistemas a lo largo del tiempo.

En Python, se puede calcular la JNF de una matriz utilizando la biblioteca NumPy y su función jordan:

In [ ]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
jordan_form = np.linalg.jordan(A)
print("Jordan Form:", jordan_form)


In [24]:
import numpy as np

A = np.array([[1, 2], [3, 4]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Autovalores:", eigenvalues)
print("Autovectores:", eigenvectors)


Autovalores: [-0.37228132  5.37228132]
Autovectores: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
